apiVersion: v1
kind: Service
metadata:
  name: kube-demo-service
  labels:
    app: kube-demo
spec:
  selector:
    app: kube-demo
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: LoadBalancer